<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    private function img(string $id): string
    {
        return "https://imagedelivery.net/VU2Gexkve1SGQTbghAvrTg/{$id}/shopitem";
    }

    private function brand(string $bg, string $fg, string $name): string
    {
        return 'https://placehold.co/400x400/' . $bg . '/' . $fg . '?text=' . urlencode($name) . '&font=montserrat';
    }

    public function run(): void
    {
        $features = json_encode(['Instant digital delivery', 'Full activation included', '24/7 support', 'Secure payment']);

        $catId = fn (string $slug) => Category::where('slug', $slug)->value('id');

        $products = [

            /* ── Education & Learning ── */
            [
                'name'              => 'DataCamp',
                'slug'              => 'datacamp',
                'description'       => 'DataCamp subscription for data science and analytics courses. Access hundreds of interactive courses in Python, R, SQL, and more.',
                'short_description' => 'Interactive data science & analytics courses.',
                'price'             => 4.99,
                'compare_price'     => 25.00,
                'discount_label'    => 'Save 80%',
                'category_id'       => $catId('education'),
                'tags'              => json_encode(['data-science', 'python', 'sql', 'analytics']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('af6b335c-4b43-414e-79dd-29caa7d31f00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Udemy',
                'slug'              => 'udemy',
                'description'       => 'Udemy premium account with access to thousands of courses across all categories.',
                'short_description' => 'Access to 200,000+ online courses.',
                'price'             => 29.99,
                'compare_price'     => 84.99,
                'discount_label'    => 'Save 65%',
                'category_id'       => $catId('education'),
                'tags'              => json_encode(['courses', 'learning', 'video']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('a19fefb5-aee4-4cde-b2e7-423aeb002a00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Busuu',
                'slug'              => 'busuu',
                'description'       => 'Busuu premium language learning subscription. Learn 14+ languages with AI-powered lessons.',
                'short_description' => 'AI-powered language learning for 14+ languages.',
                'price'             => 33.99,
                'compare_price'     => 89.99,
                'discount_label'    => 'Save 62%',
                'category_id'       => $catId('education'),
                'tags'              => json_encode(['language', 'learning', 'ai']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('e453f699-bbe6-4f48-5c83-09de25052b00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Duolingo',
                'slug'              => 'duolingo-plus',
                'description'       => 'Duolingo Plus subscription for ad-free language learning with offline access.',
                'short_description' => 'Ad-free language learning with offline mode.',
                'price'             => 24.99,
                'compare_price'     => 83.88,
                'discount_label'    => 'Save 70%',
                'category_id'       => $catId('education'),
                'tags'              => json_encode(['language', 'gamified', 'mobile']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('5f220f47-52b5-46d7-4207-f0416ca8fb00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Coursera Plus',
                'slug'              => 'coursera-plus',
                'description'       => 'Coursera Plus annual subscription with unlimited access to 7,000+ courses and certificates.',
                'short_description' => 'Unlimited access to 7,000+ courses and certificates.',
                'price'             => 27.99,
                'compare_price'     => 59.00,
                'discount_label'    => 'Save 53%',
                'category_id'       => $catId('education'),
                'tags'              => json_encode(['certificates', 'university', 'professional']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('e2b85930-79c4-4278-b6af-e0e10a79dc00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Coursera 6 Month',
                'slug'              => 'coursera-plus-copy',
                'description'       => 'Coursera Plus 6-month subscription with access to professional certificates and courses.',
                'short_description' => 'Coursera Plus for 6 months — all courses included.',
                'price'             => 14.99,
                'compare_price'     => 59.00,
                'discount_label'    => 'Save 75%',
                'category_id'       => $catId('education'),
                'tags'              => json_encode(['certificates', 'university', '6-month']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('808eadf0-03a7-4ca2-f9e7-0b451680b600'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'TryHackMe',
                'slug'              => 'tryhackme',
                'description'       => 'TryHackMe premium subscription for cybersecurity training with hands-on labs.',
                'short_description' => 'Cybersecurity training with interactive labs.',
                'price'             => 49.99,
                'compare_price'     => 120.00,
                'discount_label'    => 'Save 58%',
                'category_id'       => $catId('education'),
                'tags'              => json_encode(['cybersecurity', 'hacking', 'labs', 'ctf']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('b83209c9-7058-48a3-7db0-3d6494b23f00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],

            /* ── Streaming & Entertainment ── */
            [
                'name'              => 'Spotify',
                'slug'              => 'spotify-premium',
                'description'       => 'Spotify Premium subscription with ad-free music, offline downloads, and high-quality audio.',
                'short_description' => 'Ad-free music with offline downloads.',
                'price'             => 13.99,
                'compare_price'     => 10.99,
                'discount_label'    => null,
                'category_id'       => $catId('streaming'),
                'tags'              => json_encode(['music', 'podcast', 'offline']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('06fc36d3-692c-447b-0cf7-21fcfdcb9b00'),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Popular',
            ],
            [
                'name'              => 'Netflix',
                'slug'              => 'netflix',
                'description'       => 'Netflix Premium shared plan — 4K Ultra HD, up to 4 screens simultaneously.',
                'short_description' => '4K Ultra HD streaming on 4 screens.',
                'price'             => 5.99,
                'compare_price'     => 17.99,
                'discount_label'    => 'Save 67%',
                'category_id'       => $catId('streaming'),
                'tags'              => json_encode(['video', '4k', 'movies', 'series']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('E50914', 'FFFFFF', "NETFLIX\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Hot',
            ],
            [
                'name'              => 'Disney+',
                'slug'              => 'disney-plus',
                'description'       => 'Disney+ subscription for Disney, Marvel, Star Wars, and National Geographic.',
                'short_description' => 'Disney, Marvel, Star Wars & Nat Geo.',
                'price'             => 3.49,
                'compare_price'     => 11.99,
                'discount_label'    => 'Save 71%',
                'category_id'       => $catId('streaming'),
                'tags'              => json_encode(['disney', 'marvel', 'star-wars', 'family']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('113CCF', 'FFFFFF', "DISNEY+\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'YouTube Premium',
                'slug'              => 'youtube-premium',
                'description'       => 'YouTube Premium — ad-free videos, background play, YouTube Music included.',
                'short_description' => 'Ad-free YouTube + background play + Music.',
                'price'             => 2.99,
                'compare_price'     => 13.99,
                'discount_label'    => 'Save 79%',
                'category_id'       => $catId('streaming'),
                'tags'              => json_encode(['youtube', 'music', 'ad-free', 'offline']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('FF0000', 'FFFFFF', "YOUTUBE\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Best Seller',
            ],
            [
                'name'              => 'HBO Max',
                'slug'              => 'hbo-max',
                'description'       => 'HBO Max subscription for HBO Originals, Warner Bros. movies, and exclusive series.',
                'short_description' => 'HBO Originals, Warner Bros. & exclusive series.',
                'price'             => 4.99,
                'compare_price'     => 15.99,
                'discount_label'    => 'Save 69%',
                'category_id'       => $catId('streaming'),
                'tags'              => json_encode(['hbo', 'warner', 'movies', 'originals']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('6600FF', 'FFFFFF', "MAX\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Apple TV+',
                'slug'              => 'apple-tv-plus',
                'description'       => 'Apple TV+ subscription for award-winning Apple Original series and films.',
                'short_description' => 'Award-winning Apple Original series & films.',
                'price'             => 2.49,
                'compare_price'     => 8.99,
                'discount_label'    => 'Save 72%',
                'category_id'       => $catId('streaming'),
                'tags'              => json_encode(['apple', 'originals', 'movies', 'series']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('1C1C1E', 'FFFFFF', "APPLE TV+\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],

            /* ── AI Products ── */
            [
                'name'              => 'ChatGPT Plus',
                'slug'              => 'chatgpt-plus',
                'description'       => 'ChatGPT Plus — GPT-4o access, faster responses, advanced data analysis.',
                'short_description' => 'GPT-4o access with advanced data analysis.',
                'price'             => 9.99,
                'compare_price'     => 20.00,
                'discount_label'    => 'Save 50%',
                'category_id'       => $catId('ai-products'),
                'tags'              => json_encode(['ai', 'chatgpt', 'gpt4', 'openai']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('10A37F', 'FFFFFF', "CHATGPT\nPLUS"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Hot',
            ],
            [
                'name'              => 'Midjourney',
                'slug'              => 'midjourney',
                'description'       => 'Midjourney AI image generation — create stunning art and visuals with prompts.',
                'short_description' => 'AI image generation — stunning art from prompts.',
                'price'             => 7.99,
                'compare_price'     => 30.00,
                'discount_label'    => 'Save 73%',
                'category_id'       => $catId('ai-products'),
                'tags'              => json_encode(['ai', 'image-generation', 'art', 'design']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('1A1A2E', 'FFFFFF', "MIDJOURNEY\nPRO"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Popular',
            ],
            [
                'name'              => 'Claude Pro',
                'slug'              => 'claude-pro',
                'description'       => 'Claude Pro by Anthropic — advanced AI with 5× more usage, priority access.',
                'short_description' => 'Advanced AI with 5× usage & priority access.',
                'price'             => 11.99,
                'compare_price'     => 20.00,
                'discount_label'    => 'Save 40%',
                'category_id'       => $catId('ai-products'),
                'tags'              => json_encode(['ai', 'claude', 'anthropic', 'assistant']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('D97757', 'FFFFFF', "CLAUDE\nPRO"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Perplexity Pro',
                'slug'              => 'perplexity-pro',
                'description'       => 'Perplexity Pro — AI-powered search with real-time web data and citations.',
                'short_description' => 'AI-powered search with real-time web citations.',
                'price'             => 8.99,
                'compare_price'     => 20.00,
                'discount_label'    => 'Save 55%',
                'category_id'       => $catId('ai-products'),
                'tags'              => json_encode(['ai', 'search', 'research', 'perplexity']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('20B2AA', 'FFFFFF', "PERPLEXITY\nPRO"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Gemini Advanced',
                'slug'              => 'gemini-advanced',
                'description'       => 'Google Gemini Advanced — most capable Gemini model with 1M token context.',
                'short_description' => 'Most capable Gemini with 1M token context.',
                'price'             => 7.49,
                'compare_price'     => 19.99,
                'discount_label'    => 'Save 63%',
                'category_id'       => $catId('ai-products'),
                'tags'              => json_encode(['ai', 'google', 'gemini', 'multimodal']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('8B7CF6', 'FFFFFF', "GEMINI\nADVANCED"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'New',
            ],

            /* ── Dev & Design ── */
            [
                'name'              => 'Figma Pro',
                'slug'              => 'figma-pro',
                'description'       => 'Figma Professional plan — unlimited projects, advanced prototyping, design libraries.',
                'short_description' => 'Unlimited projects, prototyping & design libraries.',
                'price'             => 8.99,
                'compare_price'     => 15.00,
                'discount_label'    => 'Save 40%',
                'category_id'       => $catId('dev-design'),
                'tags'              => json_encode(['figma', 'design', 'prototyping', 'ui']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('F24E1E', 'FFFFFF', "FIGMA\nPROFESSIONAL"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Popular',
            ],
            [
                'name'              => 'GitHub Copilot',
                'slug'              => 'github-copilot',
                'description'       => 'GitHub Copilot Individual — AI code completion for all major IDEs.',
                'short_description' => 'AI code completion for all major IDEs.',
                'price'             => 6.99,
                'compare_price'     => 10.00,
                'discount_label'    => 'Save 30%',
                'category_id'       => $catId('dev-design'),
                'tags'              => json_encode(['github', 'ai', 'coding', 'copilot']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('24292E', 'FFFFFF', "GITHUB\nCOPILOT"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Adobe Creative CC',
                'slug'              => 'adobe-cc',
                'description'       => 'Adobe Creative Cloud — Photoshop, Illustrator, Premiere Pro, After Effects and more.',
                'short_description' => 'Photoshop, Illustrator, Premiere Pro & more.',
                'price'             => 19.99,
                'compare_price'     => 54.99,
                'discount_label'    => 'Save 64%',
                'category_id'       => $catId('dev-design'),
                'tags'              => json_encode(['adobe', 'photoshop', 'illustrator', 'video']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('FF0000', 'FFFFFF', "ADOBE CC\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Best Seller',
            ],
            [
                'name'              => 'Envato Elements',
                'slug'              => 'envato-elements',
                'description'       => 'Envato Elements — unlimited downloads of templates, fonts, graphics, and more.',
                'short_description' => 'Unlimited templates, fonts, graphics & more.',
                'price'             => 7.99,
                'compare_price'     => 16.50,
                'discount_label'    => 'Save 52%',
                'category_id'       => $catId('dev-design'),
                'tags'              => json_encode(['templates', 'graphics', 'fonts', 'assets']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('4AC367', 'FFFFFF', "ENVATO\nELEMENTS"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],

            /* ── Productivity ── */
            [
                'name'              => 'Notion Plus',
                'slug'              => 'notion-plus',
                'description'       => 'Notion Plus — unlimited blocks, file uploads, version history, and collaboration.',
                'short_description' => 'Unlimited blocks, uploads & version history.',
                'price'             => 4.99,
                'compare_price'     => 16.00,
                'discount_label'    => 'Save 69%',
                'category_id'       => $catId('productivity'),
                'tags'              => json_encode(['notion', 'notes', 'wiki', 'collaboration']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('000000', 'FFFFFF', "NOTION\nPLUS"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Popular',
            ],
            [
                'name'              => 'Grammarly Premium',
                'slug'              => 'grammarly-premium',
                'description'       => 'Grammarly Premium — advanced grammar, style suggestions, and tone detection.',
                'short_description' => 'Advanced grammar, style & tone detection.',
                'price'             => 7.99,
                'compare_price'     => 30.00,
                'discount_label'    => 'Save 73%',
                'category_id'       => $catId('productivity'),
                'tags'              => json_encode(['writing', 'grammar', 'ai', 'editing']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('15C39A', 'FFFFFF', "GRAMMARLY\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Microsoft 365',
                'slug'              => 'microsoft-365',
                'description'       => 'Microsoft 365 Family — Word, Excel, PowerPoint, Teams, OneDrive 6TB storage.',
                'short_description' => 'Word, Excel, PowerPoint + 6TB OneDrive.',
                'price'             => 5.99,
                'compare_price'     => 9.99,
                'discount_label'    => 'Save 40%',
                'category_id'       => $catId('productivity'),
                'tags'              => json_encode(['microsoft', 'office', 'word', 'excel', 'teams']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('D83B01', 'FFFFFF', "MICROSOFT\n365"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Best Seller',
            ],
            [
                'name'              => 'Canva Pro',
                'slug'              => 'canva-pro',
                'description'       => 'Canva Pro — premium templates, brand kit, background remover, unlimited storage.',
                'short_description' => 'Premium templates, brand kit & BG remover.',
                'price'             => 6.99,
                'compare_price'     => 14.99,
                'discount_label'    => 'Save 53%',
                'category_id'       => $catId('productivity'),
                'tags'              => json_encode(['canva', 'design', 'templates', 'social-media']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('00C4CC', 'FFFFFF', "CANVA\nPRO"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Hot',
            ],
            [
                'name'              => 'Loom Business',
                'slug'              => 'loom-business',
                'description'       => 'Loom Business — async video messaging, unlimited recordings, analytics.',
                'short_description' => 'Async video messaging with unlimited recordings.',
                'price'             => 4.49,
                'compare_price'     => 12.50,
                'discount_label'    => 'Save 64%',
                'category_id'       => $catId('productivity'),
                'tags'              => json_encode(['loom', 'video', 'async', 'communication']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('625DF5', 'FFFFFF', "LOOM\nBUSINESS"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],

            /* ── VPN & Security ── */
            [
                'name'              => 'NordVPN',
                'slug'              => 'nordvpn',
                'description'       => 'NordVPN Premium — 5500+ servers, 60+ countries, Threat Protection included.',
                'short_description' => '5500+ servers in 60+ countries + Threat Protection.',
                'price'             => 2.99,
                'compare_price'     => 11.99,
                'discount_label'    => 'Save 75%',
                'category_id'       => $catId('vpn-security'),
                'tags'              => json_encode(['vpn', 'nordvpn', 'privacy', 'security']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('4687FF', 'FFFFFF', "NORDVPN\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Popular',
            ],
            [
                'name'              => 'ExpressVPN',
                'slug'              => 'expressvpn',
                'description'       => 'ExpressVPN — ultra-fast VPN, trusted by millions, 105 countries.',
                'short_description' => 'Ultra-fast VPN in 105 countries.',
                'price'             => 4.99,
                'compare_price'     => 12.95,
                'discount_label'    => 'Save 61%',
                'category_id'       => $catId('vpn-security'),
                'tags'              => json_encode(['vpn', 'expressvpn', 'privacy', 'fast']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('DA3940', 'FFFFFF', "EXPRESSVPN\nPREMIUM"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Best Seller',
            ],
            [
                'name'              => 'Surfshark',
                'slug'              => 'surfshark',
                'description'       => 'Surfshark VPN — unlimited devices, strong encryption, CleanWeb ad-blocker.',
                'short_description' => 'Unlimited devices + CleanWeb ad-blocker.',
                'price'             => 1.99,
                'compare_price'     => 12.95,
                'discount_label'    => 'Save 85%',
                'category_id'       => $catId('vpn-security'),
                'tags'              => json_encode(['vpn', 'surfshark', 'unlimited', 'adblocker']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('1DB954', 'FFFFFF', "SURFSHARK\nVPN"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => '1Password',
                'slug'              => '1password',
                'description'       => '1Password password manager — secure vault, family sharing, watchtower alerts.',
                'short_description' => 'Secure vault, family sharing & watchtower alerts.',
                'price'             => 2.49,
                'compare_price'     => 4.99,
                'discount_label'    => 'Save 50%',
                'category_id'       => $catId('vpn-security'),
                'tags'              => json_encode(['password-manager', '1password', 'security', 'vault']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('1A8CFF', 'FFFFFF', "1PASSWORD\nFAMILY"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],

            /* ── Gaming ── */
            [
                'name'              => 'Xbox Game Pass',
                'slug'              => 'xbox-game-pass',
                'description'       => 'Xbox Game Pass Ultimate — 100+ games on console, PC, and cloud gaming.',
                'short_description' => '100+ games on console, PC & cloud.',
                'price'             => 4.99,
                'compare_price'     => 14.99,
                'discount_label'    => 'Save 67%',
                'category_id'       => $catId('gaming'),
                'tags'              => json_encode(['xbox', 'game-pass', 'microsoft', 'cloud-gaming']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('107C10', 'FFFFFF', "XBOX\nGAME PASS"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Popular',
            ],
            [
                'name'              => 'PlayStation Plus',
                'slug'              => 'ps-plus',
                'description'       => 'PlayStation Plus Extra — 400+ PS4/PS5 games on demand, monthly free games.',
                'short_description' => '400+ PS4/PS5 games + monthly free games.',
                'price'             => 5.99,
                'compare_price'     => 13.99,
                'discount_label'    => 'Save 57%',
                'category_id'       => $catId('gaming'),
                'tags'              => json_encode(['playstation', 'ps5', 'ps4', 'sony']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('003087', 'FFFFFF', "PS PLUS\nEXTRA"),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Hot',
            ],
            [
                'name'              => 'EA Play Pro',
                'slug'              => 'ea-play',
                'description'       => 'EA Play Pro membership — full EA library, exclusive in-game content and rewards.',
                'short_description' => 'Full EA library + exclusive in-game rewards.',
                'price'             => 2.99,
                'compare_price'     => 5.99,
                'discount_label'    => 'Save 50%',
                'category_id'       => $catId('gaming'),
                'tags'              => json_encode(['ea', 'fifa', 'battlefield', 'gaming']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('FF4500', 'FFFFFF', "EA PLAY\nPRO"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Nintendo Online',
                'slug'              => 'nintendo-online',
                'description'       => 'Nintendo Switch Online + Expansion Pack — online play, NES/SNES/N64 library.',
                'short_description' => 'Online play + NES/SNES/N64 classic library.',
                'price'             => 3.49,
                'compare_price'     => 19.99,
                'discount_label'    => 'Save 83%',
                'category_id'       => $catId('gaming'),
                'tags'              => json_encode(['nintendo', 'switch', 'online', 'retro']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->brand('E60012', 'FFFFFF', "NINTENDO\nONLINE"),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'ExitLag',
                'slug'              => 'exitlag-tier-i',
                'description'       => 'ExitLag gaming optimization — reduced ping, optimized routes, multi-path technology.',
                'short_description' => 'Reduced ping with multi-path optimization.',
                'price'             => 5.99,
                'compare_price'     => 12.00,
                'discount_label'    => 'Save 50%',
                'category_id'       => $catId('gaming'),
                'tags'              => json_encode(['gaming', 'ping', 'lag', 'optimization']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('ead9b799-f87d-45c1-b387-a62227ee6300'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Discord Nitro',
                'slug'              => 'dc-nitro-basic',
                'description'       => 'Discord Nitro — custom emojis, larger uploads, server boosts, HD streaming.',
                'short_description' => 'Custom emojis, server boosts & HD streaming.',
                'price'             => 44.99,
                'compare_price'     => 99.99,
                'discount_label'    => 'Save 55%',
                'category_id'       => $catId('gaming'),
                'tags'              => json_encode(['discord', 'nitro', 'gaming', 'community']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('433446f7-2ea1-4f56-ec73-26770a17df00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Chess.com Premium',
                'slug'              => 'chess-com-premium',
                'description'       => 'Chess.com Premium — unlimited puzzles, analysis board, video lessons, drills.',
                'short_description' => 'Unlimited puzzles, analysis & video lessons.',
                'price'             => 11.99,
                'compare_price'     => 29.99,
                'discount_label'    => 'Save 60%',
                'category_id'       => $catId('gaming'),
                'tags'              => json_encode(['chess', 'puzzles', 'strategy', 'games']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('97fdc7b9-b42c-49d2-ad41-bd81be481100'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],

            /* ── Lifestyle ── */
            [
                'name'              => 'Amazon Prime',
                'slug'              => 'amazon',
                'description'       => 'Amazon Prime — fast delivery, Prime Video, Prime Music, Prime Reading.',
                'short_description' => 'Fast delivery + Prime Video, Music & Reading.',
                'price'             => 5.99,
                'compare_price'     => 9.99,
                'discount_label'    => 'Save 40%',
                'category_id'       => $catId('lifestyle'),
                'tags'              => json_encode(['amazon', 'delivery', 'video', 'music']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('ffd726bb-afb0-42e5-8ea2-8e1586c66c00'),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Best Seller',
            ],
            [
                'name'              => 'Headspace',
                'slug'              => 'headspace-12-months',
                'description'       => 'Headspace 12-month subscription — guided meditation, sleep sounds, focus music.',
                'short_description' => 'Guided meditation, sleep sounds & focus music.',
                'price'             => 7.99,
                'compare_price'     => 69.99,
                'discount_label'    => 'Save 89%',
                'category_id'       => $catId('lifestyle'),
                'tags'              => json_encode(['meditation', 'mindfulness', 'sleep', 'wellness']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('ea342124-3d0b-4caa-75b0-c838cc1b3800'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'Tinder Gold',
                'slug'              => 'tinder-premium',
                'description'       => 'Tinder Gold — unlimited likes, Passport, Rewind, Boost and 5 Super Likes/day.',
                'short_description' => 'Unlimited likes, Passport, Rewind & Boosts.',
                'price'             => 7.99,
                'compare_price'     => 39.99,
                'discount_label'    => 'Save 80%',
                'category_id'       => $catId('lifestyle'),
                'tags'              => json_encode(['tinder', 'dating', 'social', 'premium']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('ba8f7b18-7820-43fa-a0b4-afbb8c372700'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
            [
                'name'              => 'LinkedIn Premium',
                'slug'              => 'linkedin-premium',
                'description'       => 'LinkedIn Premium Career — InMail, who viewed your profile, LinkedIn Learning.',
                'short_description' => 'InMail credits, profile viewers & LinkedIn Learning.',
                'price'             => 14.99,
                'compare_price'     => 59.99,
                'discount_label'    => 'Save 75%',
                'category_id'       => $catId('lifestyle'),
                'tags'              => json_encode(['linkedin', 'career', 'networking', 'learning']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('c8ff0b95-9806-4511-81ca-a452f79a2400'),
                'features'          => $features,
                'compliance_status' => 'approved',
                'badge'             => 'Popular',
            ],
            [
                'name'              => 'Duolingo Family',
                'slug'              => 'duolingo-family',
                'description'       => 'Duolingo Family Plan — up to 6 learners, all Plus features, progress tracking.',
                'short_description' => 'Up to 6 learners with all Plus features.',
                'price'             => 5.99,
                'compare_price'     => 9.99,
                'discount_label'    => 'Save 40%',
                'category_id'       => $catId('lifestyle'),
                'tags'              => json_encode(['duolingo', 'family', 'language', 'kids']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('5f220f47-52b5-46d7-4207-f0416ca8fb00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],

            /* ── Reseller ── */
            [
                'name'              => 'UpgraderCX Reseller',
                'slug'              => 'upgradercx-reseller',
                'description'       => 'UpgraderCX Reseller Package — access wholesale pricing, branded dashboard, and full support.',
                'short_description' => 'Wholesale pricing + branded dashboard + support.',
                'price'             => 29.99,
                'compare_price'     => null,
                'discount_label'    => null,
                'category_id'       => $catId('reseller'),
                'tags'              => json_encode(['reseller', 'wholesale', 'b2b', 'dashboard']),
                'status'            => 'active',
                'stock_status'      => 'in_stock',
                'image_url'         => $this->img('90d5c061-4065-4524-cade-46167f4dbe00'),
                'features'          => $features,
                'compliance_status' => 'approved',
            ],
        ];

        foreach ($products as $product) {
            $badge = $product['badge'] ?? null;
            unset($product['badge']);

            $product['discount_label'] = $product['discount_label'] ?? ($badge ?: null);

            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
